# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_categora', models.CharField(help_text='Nombre de la categoria', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Marca', models.CharField(help_text='Marca del Mueble', max_length=100)),
                ('nombre_mueble', models.CharField(help_text='El nombre del mueble', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='precio del mueble', max_digits=2)),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muebles.Categoria')),
            ],
        ),
    ]
